name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.17]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}

      - name: Run Tests
        run: go test -v -cover -covermode=count -coverprofile=coverage.out ./...

      - name: Convert Coverage
        uses: jandelgado/gcov2lcov-action@v1.0.8

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get Sources
        uses: actions/checkout@master

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
